org.gradle.jvmargs=-Xmx4096M -Dkotlin.daemon.jvm.options\="-Xmx4096M" -XX:+UseParallelGC
android.useAndroidX=true
android.enableJetifier=false
org.gradle.unsafe.configuration-cache=true
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=false
android.suppressUnsupportedOptionWarnings=android.suppressUnsupportedOptionWarnings,android.nonFinalResIds
org.gradle.caching=true
kotlin.incremental=true
kotlin.incremental.java=true
kotlin.caching.enabled=true
kotlin.code.style=official
