org.gradle.jvmargs=-Xmx4096M -Dkotlin.daemon.jvm.options\="-Xmx4096M" -XX:+UseParallelGC
android.useAndroidX=true
android.enableJetifier=false
org.gradle.configuration-cache=true
org.gradle.unsafe.configuration-cache=true
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=false
android.suppressUnsupportedOptionWarnings=android.suppressUnsupportedOptionWarnings,android.nonFinalResIds
org.gradle.caching=true
kotlin.incremental=true
kotlin.incremental.java=true
kotlin.caching.enabled=true
kotlin.code.style=official
org.gradle.tooling.parallel=true
kotlin.native.ignoreDisabledTargets=true
kotlin.incremental.multiplatform=true
android.enableR8.fullMode=true
kotlin.build.report.output=file
appVersion=1.0.0-a7
