package me.lampu.lampcord.shared.ui.theme

import androidx.compose.ui.graphics.Color

val ColorLightPrimary = Color(0xFF6750A4)
val ColorLightOnPrimary = Color(0xFFFFFFFF)
val ColorLightPrimaryContainer = Color(0xFFE0E0FF)
val ColorLightOnPrimaryContainer = Color(0xFF000569)
val ColorLightSecondary = Color(0xFF5C5D72)
val ColorLightOnSecondary = Color(0xFFFFFFFF)
val ColorLightSecondaryContainer = Color(0xFFE1E0F9)
val ColorLightOnSecondaryContainer = Color(0xFF191A2C)
val ColorLightTertiary = Color(0xFF78536B)
val ColorLightOnTertiary = Color(0xFFFFFFFF)
val ColorLightTertiaryContainer = Color(0xFFFFD7EE)
val ColorLightOnTertiaryContainer = Color(0xFF2E1126)
val ColorLightError = Color(0xFFBA1A1A)
val ColorLightErrorContainer = Color(0xFFFFDAD6)
val ColorLightOnError = Color(0xFFFFFFFF)
val ColorLightOnErrorContainer = Color(0xFF410002)
val ColorLightBackground = Color(0xFFFFFBFF)
val ColorLightOnBackground = Color(0xFF1B1B1F)
val ColorLightSurface = Color(0xFFFFFBFF)
val ColorLightOnSurface = Color(0xFF1B1B1F)
val ColorLightSurfaceVariant = Color(0xFFE3E1EC)
val ColorLightOnSurfaceVariant = Color(0xFF46464F)
val ColorLightOutline = Color(0xFF777680)
val ColorLightInverseOnSurface = Color(0xFFF3F0F4)
val ColorLightInverseSurface = Color(0xFF303034)
val ColorLightInversePrimary = Color(0xFFBEC2FF)
val ColorLightSurfaceTint = Color(0xFF3F4CDA)
val ColorLightOutlineVariant = Color(0xFFC7C5D0)
val ColorLightScrim = Color(0xFF000000)

val ColorDarkPrimary = Color(0xFFBEC2FF)
val ColorDarkOnPrimary = Color(0xFF000DA4)
val ColorDarkPrimaryContainer = Color(0xFF222FC2)
val ColorDarkOnPrimaryContainer = Color(0xFFE0E0FF)
val ColorDarkSecondary = Color(0xFFC5C4DD)
val ColorDarkOnSecondary = Color(0xFF2E2F42)
val ColorDarkSecondaryContainer = Color(0xFF444559)
val ColorDarkOnSecondaryContainer = Color(0xFFE1E0F9)
val ColorDarkTertiary = Color(0xFFE7B9D5)
val ColorDarkOnTertiary = Color(0xFF45263C)
val ColorDarkTertiaryContainer = Color(0xFF5E3C53)
val ColorDarkOnTertiaryContainer = Color(0xFFFFD7EE)
val ColorDarkError = Color(0xFFFFB4AB)
val ColorDarkErrorContainer = Color(0xFF93000A)
val ColorDarkOnError = Color(0xFF690005)
val ColorDarkOnErrorContainer = Color(0xFFFFDAD6)
val ColorDarkBackground = Color(0xFF1B1B1F)
val ColorDarkOnBackground = Color(0xFFE4E1E6)
val ColorDarkSurface = Color(0xFF1B1B1F)
val ColorDarkOnSurface = Color(0xFFE4E1E6)
val ColorDarkSurfaceVariant = Color(0xFF46464F)
val ColorDarkOnSurfaceVariant = Color(0xFFC7C5D0)
val ColorDarkOutline = Color(0xFF91909A)
val ColorDarkInverseOnSurface = Color(0xFF1B1B1F)
val ColorDarkInverseSurface = Color(0xFFE4E1E6)
val ColorDarkInversePrimary = Color(0xFF3F4CDA)
val ColorDarkSurfaceTint = Color(0xFFBEC2FF)
val ColorDarkOutlineVariant = Color(0xFF46464F)
val ColorDarkScrim = Color(0xFF000000)

val Blurple = Color(0xFF5865F2)
val Green = Color(0xFF57F287)
val Yellow = Color(0xFFFEE75C)
val Fuchsia = Color(0xFFEB459E)

val DiscordGreen = Color(0xFF23A559)
val DiscordYellow = Color(0xFFF0B232)
val DiscordRed = Color(0xFFF23F43)
val DiscordGray = Color(0xFF80848E)

// Legacy Discord 126.21 Colors
val DiscordClassicBackground = Color(0xFF36393F)
val DiscordClassicSidebar = Color(0xFF2F3136)
val DiscordClassicGuildRail = Color(0xFF202225)
val DiscordClassicDarkHeader = Color(0xFF18191C)
val DiscordClassicSelected = Color(0xFF42464D)
val DiscordClassicHover = Color(0xFF393C43)
val DiscordClassicTextTitle = Color(0xFFFFFFFF)
val DiscordClassicTextBody = Color(0xFFDCDDDE)
val DiscordClassicTextMuted = Color(0xFF72767D)
val DiscordClassicBlurple = Color(0xFF5865F2)
