@file:Suppress("ktlint:standard:max-line-length")

package com.example.materialcord.shared.ui.icons

import androidx.compose.ui.graphics.vector.ImageVector

// Generated by scripts/generate_material_symbols.py from Google Material Symbols.
object MaterialcordIconsFilled {
    val AccountCircle: ImageVector by lazy {
        materialSymbol(
            name = "Filled.AccountCircle",
            pathData = "M234-276q51-39 114-61.5T480-360q69 0 132 22.5T726-276q35-41 54.5-93T800-480q0-133-93.5-226.5T480-800q-133 0-226.5 93.5T160-480q0 59 19.5 111t54.5 93Zm146.5-204.5Q340-521 340-580t40.5-99.5Q421-720 480-720t99.5 40.5Q620-639 620-580t-40.5 99.5Q539-440 480-440t-99.5-40.5ZM480-80q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Z",
        )
    }

    val Add: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Add",
            pathData = "M440-440H200v-80h240v-240h80v240h240v80H520v240h-80v-240Z",
        )
    }

    val Album: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Album",
            pathData = "M480-300q75 0 127.5-52.5T660-480q0-75-52.5-127.5T480-660q-75 0-127.5 52.5T300-480q0 75 52.5 127.5T480-300Zm-28.5-151.5Q440-463 440-480t11.5-28.5Q463-520 480-520t28.5 11.5Q520-497 520-480t-11.5 28.5Q497-440 480-440t-28.5-11.5ZM480-80q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Z",
        )
    }

    val BarChart4Bars: ImageVector by lazy {
        materialSymbol(
            name = "Filled.BarChart4Bars",
            pathData = "M80-120v-80h800v80H80Zm40-120v-280h120v280H120Zm200 0v-480h120v480H320Zm200 0v-360h120v360H520Zm200 0v-600h120v600H720Z",
        )
    }

    val SportsEsports: ImageVector by lazy {
        materialSymbol(
            name = "Filled.SportsEsports",
            pathData = "M182-200q-51 0-79-35.5T82-322l42-300q9-60 53.5-99T282-760h396q60 0 104.5 39t53.5 99l42 300q7 51-21 86.5T778-200q-21 0-39-7.5T706-230l-90-90H344l-90 90q-15 15-33 22.5t-39 7.5Zm526.5-251.5Q720-463 720-480t-11.5-28.5Q697-520 680-520t-28.5 11.5Q640-497 640-480t11.5 28.5Q663-440 680-440t28.5-11.5Zm-80-120Q640-583 640-600t-11.5-28.5Q617-640 600-640t-28.5 11.5Q560-617 560-600t11.5 28.5Q583-560 600-560t28.5-11.5ZM310-440h60v-70h70v-60h-70v-70h-60v70h-70v60h70v70Z",
        )
    }

    val Tv: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Tv",
            pathData = "M320-120v-80H160q-33 0-56.5-23.5T80-280v-480q0-33 23.5-56.5T160-840h640q33 0 56.5 23.5T880-760v480q0 33-23.5 56.5T800-200H640v80H320Z",
        )
    }

    val HourglassBottom: ImageVector by lazy {
        materialSymbol(
            name = "Filled.HourglassBottom",
            pathData = "M593-567q47-47 47-113v-120H320v120q0 66 47 113t113 47q66 0 113-47ZM160-80v-80h80v-120q0-61 28.5-114.5T348-480q-51-32-79.5-85.5T240-680v-120h-80v-80h640v80h-80v120q0 61-28.5 114.5T612-480q51 32 79.5 85.5T720-280v120h80v80H160Z",
        )
    }

    val BarChart: ImageVector by lazy {
        materialSymbol(
            name = "Filled.BarChart",
            pathData = "M640-160v-280h160v280H640Zm-240 0v-640h160v640H400Zm-240 0v-440h160v440H160Z",
        )
    }

    val Bedtime: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Bedtime",
            pathData = "M484-80q-84 0-157.5-32t-128-86.5Q144-253 112-326.5T80-484q0-146 93-257.5T410-880q-18 99 11 193.5T521-521q71 71 165.5 100T880-410q-26 144-138 237T484-80Z",
        )
    }

    val BrokenImage: ImageVector by lazy {
        materialSymbol(
            name = "Filled.BrokenImage",
            pathData = "M200-120q-33 0-56.5-23.5T120-200v-264l120 120 160-160 160 160 160-160 120 120v184q0 33-23.5 56.5T760-120H200Zm0-720h560q33 0 56.5 23.5T840-760v263L720-617 560-457 400-617 240-457 120-577v-183q0-33 23.5-56.5T200-840Z",
        )
    }

    val Check: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Check",
            pathData = "M382-240 154-468l57-57 171 171 367-367 57 57-424 424Z",
        )
    }

    val ChevronLeft: ImageVector by lazy {
        materialSymbol(
            name = "Filled.ChevronLeft",
            pathData = "M560-240 320-480l240-240 56 56-184 184 184 184-56 56Z",
        )
    }

    val ChevronRight: ImageVector by lazy {
        materialSymbol(
            name = "Filled.ChevronRight",
            pathData = "M504-480 320-664l56-56 240 240-240 240-56-56 184-184Z",
        )
    }

    val KeyboardArrowDown: ImageVector by lazy {
        materialSymbol(
            name = "Filled.KeyboardArrowDown",
            pathData = "M480-344 240-584l56-56 184 184 184-184 56 56-240 240Z",
        )
    }

    val Clear: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Clear",
            pathData = "m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z",
        )
    }

    val Close: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Close",
            pathData = "m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z",
        )
    }

    val ContentCopy: ImageVector by lazy {
        materialSymbol(
            name = "Filled.ContentCopy",
            pathData = "M360-240q-33 0-56.5-23.5T280-320v-480q0-33 23.5-56.5T360-880h360q33 0 56.5 23.5T800-800v480q0 33-23.5 56.5T720-240H360ZM200-80q-33 0-56.5-23.5T120-160v-560h80v560h440v80H200Z",
        )
    }

    val CropSquare: ImageVector by lazy {
        materialSymbol(
            name = "Filled.CropSquare",
            pathData = "M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Z",
        )
    }

    val Delete: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Delete",
            pathData = "M280-120q-33 0-56.5-23.5T200-200v-520h-40v-80h200v-40h240v40h200v80h-40v520q0 33-23.5 56.5T680-120H280Zm80-160h80v-360h-80v360Zm160 0h80v-360h-80v360Z",
        )
    }

    val Download: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Download",
            pathData = "M480-320 280-520l56-58 104 104v-326h80v326l104-104 56 58-200 200ZM240-160q-33 0-56.5-23.5T160-240v-120h80v120h480v-120h80v120q0 33-23.5 56.5T720-160H240Z",
        )
    }

    val DragIndicator: ImageVector by lazy {
        materialSymbol(
            name = "Filled.DragIndicator",
            pathData = "M360-160q-33 0-56.5-23.5T280-240q0-33 23.5-56.5T360-320q33 0 56.5 23.5T440-240q0 33-23.5 56.5T360-160Zm240 0q-33 0-56.5-23.5T520-240q0-33 23.5-56.5T600-320q33 0 56.5 23.5T680-240q0 33-23.5 56.5T600-160ZM360-400q-33 0-56.5-23.5T280-480q0-33 23.5-56.5T360-560q33 0 56.5 23.5T440-480q0 33-23.5 56.5T360-400Zm240 0q-33 0-56.5-23.5T520-480q0-33 23.5-56.5T600-560q33 0 56.5 23.5T680-480q0 33-23.5 56.5T600-400ZM360-640q-33 0-56.5-23.5T280-720q0-33 23.5-56.5T360-800q33 0 56.5 23.5T440-720q0 33-23.5 56.5T360-640Zm240 0q-33 0-56.5-23.5T520-720q0-33 23.5-56.5T600-800q33 0 56.5 23.5T680-720q0 33-23.5 56.5T600-640Z",
        )
    }

    val Edit: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Edit",
            pathData = "M120-120v-170l528-527q12-11 26.5-17t30.5-6q16 0 31 6t26 18l55 56q12 11 17.5 26t5.5 30q0 16-5.5 30.5T817-647L290-120H120Zm584-528 56-56-56-56-56 56 56 56Z",
        )
    }

    val Error: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Error",
            pathData = "M508.5-291.5Q520-303 520-320t-11.5-28.5Q497-360 480-360t-28.5 11.5Q440-337 440-320t11.5 28.5Q463-280 480-280t28.5-11.5ZM440-440h80v-240h-80v240Zm40 360q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Z",
        )
    }

    val Folder: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Folder",
            pathData = "M160-160q-33 0-56.5-23.5T80-240v-480q0-33 23.5-56.5T160-800h240l80 80h320q33 0 56.5 23.5T880-640v400q0 33-23.5 56.5T760-160H160Z",
        )
    }

    val FolderOpen: ImageVector by lazy {
        materialSymbol(
            name = "Filled.FolderOpen",
            pathData = "M160-160q-33 0-56.5-23.5T80-240v-480q0-33 23.5-56.5T160-800h240l80 80h320q33 0 56.5 23.5T880-640v400q0 33-23.5 56.5T760-160H160Zm0-80h600v-320H160v320Zm0-400h600v-80H457l-80-80H160v160Zm0 400v-320 320Z",
        )
    }

    val Favorite: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Favorite",
            pathData = "m480-120-58-52q-101-91-167-157T150-447.5Q111-500 95.5-544T80-634q0-94 63-157t157-63q52 0 99 22t81 62q34-40 81-62t99-22q94 0 157 63t63 157q0 46-15.5 90T810-447.5Q771-395 705-329T538-172l-58 52Z",
        )
    }

    val FavoriteBorder: ImageVector by lazy {
        materialSymbol(
            name = "Filled.FavoriteBorder",
            pathData = "m480-120-58-52q-101-91-167-157T150-447.5Q111-500 95.5-544T80-634q0-94 63-157t157-63q52 0 99 22t81 62q34-40 81-62t99-22q94 0 157 63t63 157q0 46-15.5 90T810-447.5Q771-395 705-329T538-172l-58 52Zm0-108q96-86 158-147.5t98-107q36-45.5 50-81t14-70.5q0-60-40-100t-100-40q-47 0-87 26.5T518-680h-76q-15-41-55-67.5T300-774q-60 0-100 40t-40 100q0 35 14 70.5t50 81q36 45.5 98 107T480-228Zm0-273Z",
        )
    }

    val Fullscreen: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Fullscreen",
            pathData = "M120-120v-200h80v120h120v80H120Zm520 0v-80h120v-120h80v200H640ZM120-640v-200h200v80H200v120h-80Zm640 0v-120H640v-80h200v200h-80Z",
        )
    }

    val FullscreenExit: ImageVector by lazy {
        materialSymbol(
            name = "Filled.FullscreenExit",
            pathData = "M240-120v-120H120v-80h200v200h-80Zm400 0v-200h200v80H720v120h-80ZM120-640v-80h120v-120h80v200H120Zm520 0v-200h80v120h120v80H640Z",
        )
    }

    val GridView: ImageVector by lazy {
        materialSymbol(
            name = "Filled.GridView",
            pathData = "M120-520v-320h320v320H120Zm0 400v-320h320v320H120Zm400-400v-320h320v320H520Zm0 400v-320h320v320H520Z",
        )
    }

    val Groups: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Groups",
            pathData = "M0-240v-63q0-43 44-70t116-27q13 0 25 .5t23 2.5q-14 21-21 44t-7 48v65H0Zm240 0v-65q0-32 17.5-58.5T307-410q32-20 76.5-30t96.5-10q53 0 97.5 10t76.5 30q32 20 49 46.5t17 58.5v65H240Zm540 0v-65q0-26-6.5-49T754-397q11-2 22.5-2.5t23.5-.5q72 0 116 26.5t44 70.5v63H780ZM160-440q-33 0-56.5-23.5T80-520q0-34 23.5-57t56.5-23q34 0 57 23t23 57q0 33-23 56.5T160-440Zm640 0q-33 0-56.5-23.5T720-520q0-34 23.5-57t56.5-23q34 0 57 23t23 57q0 33-23 56.5T800-440Zm-320-40q-50 0-85-35t-35-85q0-51 35-85.5t85-34.5q51 0 85.5 34.5T600-600q0 50-34.5 85T480-480Z",
        )
    }

    val Headphones: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Headphones",
            pathData = "M360-120H200q-33 0-56.5-23.5T120-200v-280q0-75 28.5-140.5t77-114q48.5-48.5 114-77T480-840q75 0 140.5 28.5t114 77q48.5 48.5 77 114T840-480v280q0 33-23.5 56.5T760-120H600v-320h160v-40q0-117-81.5-198.5T480-760q-117 0-198.5 81.5T200-480v40h160v320Z",
        )
    }

    val History: ImageVector by lazy {
        materialSymbol(
            name = "Filled.History",
            pathData = "M480-120q-138 0-240.5-91.5T122-440h82q14 104 92.5 172T480-200q117 0 198.5-81.5T760-480q0-117-81.5-198.5T480-760q-69 0-129 32t-101 88h110v80H120v-240h80v94q51-64 124.5-99T480-840q75 0 140.5 28.5t114 77q48.5 48.5 77 114T840-480q0 75-28.5 140.5t-77 114q-48.5 48.5-114 77T480-120Zm112-192L440-464v-216h80v184l128 128-56 56Z",
        )
    }

    val Home: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Home",
            pathData = "M160-120v-480l320-240 320 240v480H560v-280H400v280H160Z",
        )
    }

    val HorizontalRule: ImageVector by lazy {
        materialSymbol(
            name = "Filled.HorizontalRule",
            pathData = "M160-440v-80h640v80H160Z",
        )
    }

    val Info: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Info",
            pathData = "M440-280h80v-240h-80v240Zm68.5-331.5Q520-623 520-640t-11.5-28.5Q497-680 480-680t-28.5 11.5Q440-657 440-640t11.5 28.5Q463-600 480-600t28.5-11.5ZM480-80q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Z",
        )
    }

    val LibraryMusic: ImageVector by lazy {
        materialSymbol(
            name = "Filled.LibraryMusic",
            pathData = "M500-360q42 0 71-29t29-71v-220h120v-80H560v220q-13-10-28-15t-32-5q-42 0-71 29t-29 71q0 42 29 71t71 29ZM320-240q-33 0-56.5-23.5T240-320v-480q0-33 23.5-56.5T320-880h480q33 0 56.5 23.5T880-800v480q0 33-23.5 56.5T800-240H320ZM160-80q-33 0-56.5-23.5T80-160v-560h80v560h560v80H160Z",
        )
    }

    val Link: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Link",
            pathData = "M440-280H280q-83 0-141.5-58.5T80-480q0-83 58.5-141.5T280-680h160v80H280q-50 0-85 35t-35 85q0 50 35 85t85 35h160v80ZM320-440v-80h320v80H320Zm200 160v-80h160q50 0 85-35t35-85q0-50-35-85t-85-35H520v-80h160q83 0 141.5 58.5T880-480q0 83-58.5 141.5T680-280H520Z",
        )
    }

    val Lyrics: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Lyrics",
            pathData = "M80-80v-720q0-33 23.5-56.5T160-880h440q33 0 56.5 23.5T680-800v17q-24 11-44 27t-36 36v-80H160v527l47-47h393v-160q16 20 36 36t44 27v97q0 33-23.5 56.5T600-240H240L80-80Zm160-320h160v-80H240v80Zm520-80q-50 0-85-35t-35-85q0-50 35-85t85-35q11 0 21 2t19 5v-207h160v80h-80v240q0 50-35 85t-85 35Zm-520-40h280v-80H240v80Zm0-120h280v-80H240v80Zm-80 320v-480 480Z",
        )
    }

    val Menu: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Menu",
            pathData = "M120-240v-80h720v80H120Zm0-200v-80h720v80H120Zm0-200v-80h720v80H120Z",
        )
    }

    val MoreHoriz: ImageVector by lazy {
        materialSymbol(
            name = "Filled.MoreHoriz",
            pathData = "M240-400q-33 0-56.5-23.5T160-480q0-33 23.5-56.5T240-560q33 0 56.5 23.5T320-480q0 33-23.5 56.5T240-400Zm240 0q-33 0-56.5-23.5T400-480q0-33 23.5-56.5T480-560q33 0 56.5 23.5T560-480q0 33-23.5 56.5T480-400Zm240 0q-33 0-56.5-23.5T640-480q0-33 23.5-56.5T720-560q33 0 56.5 23.5T800-480q0 33-23.5 56.5T720-400Z",
        )
    }

    val MoreVert: ImageVector by lazy {
        materialSymbol(
            name = "Filled.MoreVert",
            pathData = "M480-160q-33 0-56.5-23.5T400-240q0-33 23.5-56.5T480-320q33 0 56.5 23.5T560-240q0 33-23.5 56.5T480-160Zm0-240q-33 0-56.5-23.5T400-480q0-33 23.5-56.5T480-560q33 0 56.5 23.5T560-480q0 33-23.5 56.5T480-400Zm0-240q-33 0-56.5-23.5T400-720q0-33 23.5-56.5T480-800q33 0 56.5 23.5T560-720q0 33-23.5 56.5T480-640Z",
        )
    }

    val MusicNote: ImageVector by lazy {
        materialSymbol(
            name = "Filled.MusicNote",
            pathData = "M287-167q-47-47-47-113t47-113q47-47 113-47 23 0 42.5 5.5T480-418v-422h240v160H560v400q0 66-47 113t-113 47q-66 0-113-47Z",
        )
    }

    val Pause: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Pause",
            pathData = "M560-200v-560h160v560H560Zm-320 0v-560h160v560H240Z",
        )
    }

    val Person: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Person",
            pathData = "M367-527q-47-47-47-113t47-113q47-47 113-47t113 47q47 47 47 113t-47 113q-47 47-113 47t-113-47ZM160-160v-112q0-34 17.5-62.5T224-378q62-31 126-46.5T480-440q66 0 130 15.5T736-378q29 15 46.5 43.5T800-272v112H160Z",
        )
    }

    val PersonAdd: ImageVector by lazy {
        materialSymbol(
            name = "Filled.PersonAdd",
            pathData = "M720-400v-120H600v-80h120v-120h80v120h120v80H800v120h-80ZM247-527q-47-47-47-113t47-113q47-47 113-47t113 47q47 47 47 113t-47 113q-47 47-113 47t-113-47ZM40-160v-112q0-34 17.5-62.5T104-378q62-31 126-46.5T360-440q66 0 130 15.5T616-378q29 15 46.5 43.5T680-272v112H40Z",
        )
    }

    val PlayArrow: ImageVector by lazy {
        materialSymbol(
            name = "Filled.PlayArrow",
            pathData = "M320-200v-560l440 280-440 280Z",
        )
    }

    val Podcasts: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Podcasts",
            pathData = "M440-80v-331q-18-11-29-28.5T400-480q0-33 23.5-56.5T480-560q33 0 56.5 23.5T560-480q0 23-11 41t-29 28v331h-80ZM204-190q-57-55-90.5-129.5T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 86-33.5 161T756-190l-56-56q46-44 73-104.5T800-480q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 69 27 129t74 104l-57 57Zm113-113q-35-33-56-78.5T240-480q0-100 70-170t170-70q100 0 170 70t70 170q0 53-21 99t-56 78l-57-57q25-23 39.5-54t14.5-66q0-66-47-113t-113-47q-66 0-113 47t-47 113q0 36 14.5 66.5T374-360l-57 57Z",
        )
    }

    val PushPin: ImageVector by lazy {
        materialSymbol(
            name = "Filled.PushPin",
            pathData = "m640-480 80 80v80H520v240l-40 40-40-40v-240H240v-80l80-80v-280h-40v-80h400v80h-40v280Z",
        )
    }

    val QuestionMark: ImageVector by lazy {
        materialSymbol(
            name = "Filled.QuestionMark",
            pathData = "M424-320q0-81 14.5-116.5T500-514q41-36 62.5-62.5T584-637q0-41-27.5-68T480-732q-51 0-77.5 31T365-638l-103-44q21-64 77-111t141-47q105 0 161.5 58.5T698-641q0 50-21.5 85.5T609-475q-49 47-59.5 71.5T539-320H424Zm56 240q-33 0-56.5-23.5T400-160q0-33 23.5-56.5T480-240q33 0 56.5 23.5T560-160q0 33-23.5 56.5T480-80Z",
        )
    }

    val Radio: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Radio",
            pathData = "M160-80q-33 0-56.5-23.5T80-160v-534l556-226 26 66-330 134h468q33 0 56.5 23.5T880-640v480q0 33-23.5 56.5T800-80H160Zm231-149q29-29 29-71t-29-71q-29-29-71-29t-71 29q-29 29-29 71t29 71q29 29 71 29t71-29ZM160-520h480v-80h80v80h80v-120H160v120Z",
        )
    }

    val Refresh: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Refresh",
            pathData = "M480-160q-134 0-227-93t-93-227q0-134 93-227t227-93q69 0 132 28.5T720-690v-110h80v280H520v-80h168q-32-56-87.5-88T480-720q-100 0-170 70t-70 170q0 100 70 170t170 70q77 0 139-44t87-116h84q-28 106-114 173t-196 67Z",
        )
    }

    val Remove: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Remove",
            pathData = "M200-440v-80h560v80H200Z",
        )
    }

    val Repeat: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Repeat",
            pathData = "M280-80 120-240l160-160 56 58-62 62h406v-160h80v240H274l62 62-56 58Zm-80-440v-240h486l-62-62 56-58 160 160-160 160-56-58 62-62H280v160h-80Z",
        )
    }

    val RepeatOne: ImageVector by lazy {
        materialSymbol(
            name = "Filled.RepeatOne",
            pathData = "M460-360v-180h-60v-60h120v240h-60ZM280-80 120-240l160-160 56 58-62 62h406v-160h80v240H274l62 62-56 58Zm-80-440v-240h486l-62-62 56-58 160 160-160 160-56-58 62-62H280v160h-80Z",
        )
    }

    val Search: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Search",
            pathData = "M784-120 532-372q-30 24-69 38t-83 14q-109 0-184.5-75.5T120-580q0-109 75.5-184.5T380-840q109 0 184.5 75.5T640-580q0 44-14 83t-38 69l252 252-56 56ZM380-400q75 0 127.5-52.5T560-580q0-75-52.5-127.5T380-760q-75 0-127.5 52.5T200-580q0 75 52.5 127.5T380-400Z",
        )
    }

    val SearchOff: ImageVector by lazy {
        materialSymbol(
            name = "Filled.SearchOff",
            pathData = "M138.5-138.5Q80-197 80-280t58.5-141.5Q197-480 280-480t141.5 58.5Q480-363 480-280t-58.5 141.5Q363-80 280-80t-141.5-58.5ZM824-120 568-376q-12-13-25.5-26.5T516-428q38-24 61-64t23-88q0-75-52.5-127.5T420-760q-75 0-127.5 52.5T240-580q0 6 .5 11.5T242-557q-18 2-39.5 8T164-535q-2-11-3-22t-1-23q0-109 75.5-184.5T420-840q109 0 184.5 75.5T680-580q0 43-13.5 81.5T629-428l251 252-56 56Zm-615-61 71-71 70 71 29-28-71-71 71-71-28-28-71 71-71-71-28 28 71 71-71 71 28 28Z",
        )
    }

    val Settings: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Settings",
            pathData = "m370-80-16-128q-13-5-24.5-12T307-235l-119 50L78-375l103-78q-1-7-1-13.5v-27q0-6.5 1-13.5L78-585l110-190 119 50q11-8 23-15t24-12l16-128h220l16 128q13 5 24.5 12t22.5 15l119-50 110 190-103 78q1 7 1 13.5v27q0 6.5-2 13.5l103 78-110 190-118-50q-11 8-23 15t-24 12L590-80H370Zm112-260q58 0 99-41t41-99q0-58-41-99t-99-41q-59 0-99.5 41T342-480q0 58 40.5 99t99.5 41Z",
        )
    }

    val Share: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Share",
            pathData = "M680-80q-50 0-85-35t-35-85q0-6 3-28L282-392q-16 15-37 23.5t-45 8.5q-50 0-85-35t-35-85q0-50 35-85t85-35q24 0 45 8.5t37 23.5l281-164q-2-7-2.5-13.5T560-760q0-50 35-85t85-35q50 0 85 35t35 85q0 50-35 85t-85 35q-24 0-45-8.5T598-672L317-508q2 7 2.5 13.5t.5 14.5q0 8-.5 14.5T317-452l281 164q16-15 37-23.5t45-8.5q50 0 85 35t35 85q0 50-35 85t-85 35Z",
        )
    }

    val Shuffle: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Shuffle",
            pathData = "M560-160v-80h104L537-367l57-57 126 126v-102h80v240H560Zm-344 0-56-56 504-504H560v-80h240v240h-80v-104L216-160Zm151-377L160-744l56-56 207 207-56 56Z",
        )
    }

    val SkipNext: ImageVector by lazy {
        materialSymbol(
            name = "Filled.SkipNext",
            pathData = "M660-240v-480h80v480h-80Zm-440 0v-480l360 240-360 240Z",
        )
    }

    val Speed: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Speed",
            pathData = "M418-340q25 25 63 23.5t55-27.5l224-336-336 224q-26 18-28.5 54.5T418-340ZM204-160q-22 0-40.5-9.5T134-198q-26-47-40-97.5T80-400q0-83 31.5-156T197-683q54-54 127-85.5T480-800q82 0 154 31t126 84.5q54 53.5 86 125T879-406q1 55-12.5 107.5T825-198q-11 19-29.5 28.5T755-160H204Z",
        )
    }

    val Star: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Star",
            pathData = "m233-120 65-281L80-590l288-25 112-265 112 265 288 25-218 189 65 281-247-149-247 149Z",
        )
    }

    val Sync: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Sync",
            pathData = "M160-160v-80h110l-16-14q-49-49-71.5-106.5T160-478q0-111 66.5-197.5T400-790v84q-72 26-116 88.5T240-478q0 45 17 87.5t53 78.5l10 10v-98h80v240H160Zm400-10v-84q72-26 116-88.5T720-482q0-45-17-87.5T650-648l-10-10v98h-80v-240h240v80H690l16 14q49 49 71.5 106.5T800-482q0 111-66.5 197.5T560-170Z",
        )
    }

    val Visibility: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Visibility",
            pathData = "M607.5-372.5Q660-425 660-500t-52.5-127.5Q555-680 480-680t-127.5 52.5Q300-575 300-500t52.5 127.5Q405-320 480-320t127.5-52.5Zm-204-51Q372-455 372-500t31.5-76.5Q435-608 480-608t76.5 31.5Q588-545 588-500t-31.5 76.5Q525-392 480-392t-76.5-31.5ZM214-281.5Q94-363 40-500q54-137 174-218.5T480-800q146 0 266 81.5T920-500q-54 137-174 218.5T480-200q-146 0-266-81.5Z",
        )
    }

    val VisibilityOff: ImageVector by lazy {
        materialSymbol(
            name = "Filled.VisibilityOff",
            pathData = "M792-56 624-222q-35 11-70.5 16.5T480-200q-151 0-269-83.5T40-500q21-53 53-98.5t73-81.5L56-792l56-56 736 736-56 56ZM480-320q11 0 20.5-1t20.5-4L305-541q-3 11-4 20.5t-1 20.5q0 75 52.5 127.5T480-320Zm292 18L645-428q7-17 11-34.5t4-37.5q0-75-52.5-127.5T480-680q-20 0-37.5 4T408-664L306-766q41-17 84-25.5t90-8.5q151 0 269 83.5T920-500q-23 59-60.5 109.5T772-302ZM587-486 467-606q28-5 51.5 4.5T559-574q17 18 24.5 41.5T587-486Z",
        )
    }

    val Warning: ImageVector by lazy {
        materialSymbol(
            name = "Filled.Warning",
            pathData = "m40-120 440-760 440 760H40Zm468.5-131.5Q520-263 520-280t-11.5-28.5Q497-320 480-320t-28.5 11.5Q440-297 440-280t11.5 28.5Q463-240 480-240t28.5-11.5ZM440-360h80v-200h-80v200Z",
        )
    }
}
